site_name: spatialdata_xenium_explorer
repo_name: spatialdata_xenium_explorer
copyright: Copyright &copy; 2023 - 2024 Quentin Blampey
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - CLI: cli.md
  - API: api.md
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
